version: '3.8'

services:
  database:
    platform: linux/x86_64
    image: mysql:8
    ports:
        - "33061:3306"
    command: --init-file /data/application/init.sql
    restart: always
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      prova:

  app:
    image: prova-adonis-js
    depends_on:
      - "database"
    build: .
    ports: 
      - '3333:3333'
    volumes:
      - .:/app
    restart: on-failure
    entrypoint: [ "./wait-for.sh", "database:3306", "--", "yarn", "start" ]
    environment:
     - PORT=3333
     - NODE_ENV=development
     - APP_KEY=Tzb3-6N_U4CO6YssT9D-WE_FAz4ep7BN
     - DRIVE_DISK=local
     - DB_CONNECTION=mysql
     - TZ=America/Campo_Grande
     - SMTP_HOST=smtp.mailtrap.io
     - SMTP_PORT=2525
     - SMTP_USERNAME=58084adc95c9f0
     - SMTP_PASSWORD=6c236dd4ff89aa
     - CACHE_VIEWS=false
     - MYSQL_HOST=database
     - MYSQL_PORT=3306
     - MYSQL_USER=lucid
     - MYSQL_PASSWORD=provaadonis
     - MYSQL_DB_NAME=prova_adonis_js
    links:
      - database
    networks:
      prova:
  
networks:
  prova:
    driver: bridge